CREATE SCHEMA IF NOT EXISTS PUBLIC;
CREATE TABLE IF NOT EXISTS PUBLIC.Object;
CREATE TABLE IF NOT EXISTS PUBLIC.objectvalue;
CREATE TABLE IF NOT EXISTS PUBLIC.objecttypeattribute;
CREATE TABLE IF NOT EXISTS PUBLIC.attribute;
CREATE TABLE IF NOT EXISTS PUBLIC.objecttype;