package com.opitz.iotprototype

import com.opitz.iotprototype.entities.User;
import java.util.HashSet;

rule "Switch ON Wohnzimmer for Pascal"
when
   u : User( username == "Pascal" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "Wohnzimmer" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON Wohnzimmer for Pascal ##" );
end

rule "Switch ON Office for PascalsAir"
when
   u : User( username == "PascalsAir" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "Office" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON Office for PascalsAir ##" );
end

rule "Switch ON bathroom and meetingroom for daniel"
when
   u : User( username == "daniel" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "bathroom" );
   specials.add( "meetingroom" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON bathroom and meetingroom for daniel ##" );
end
