package com.opitz.iotprototype

import com.opitz.iotprototype.entities.User;
import java.util.HashSet;

rule "Switch OFF chilloutArea for jack"
when
   u : User( username == "jack" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "chilloutArea" );
   insert( specials );
   System.out.println("## drools: special rule to switch OFF chilloutArea for jack ##");
end

rule "Switch OFF Office for PascalsAir"
when
   u : User( username == "PascalsAir" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "Office" );
   insert( specials );
   System.out.println( "## drools: special rule to switch OFF Office for PascalsAir ##" );
end

rule "Switch OFF bathroom and meetingroom for daniel"
when
   u : User( username == "daniel" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "bathroom" );
   specials.add( "meetingroom" );
   insert( specials );
   System.out.println( "## drools: special rule to switch OFF bathroom and meetingroom for daniel ##" );
end